### ISSUE TITLE
Busting wins instead of losing

### ISSUE THREAD

**Issue by anicholson** [gdonald/blackjack-cr#1]
Scenario:

I hit and my score exceeds 21.

Expected: I bust and lose the hand.
Actual: I automatically win the hand!

![image](https://user-images.githubusercontent.com/95196/51875695-1b466c00-23ba-11e9-98bf-dd46e72c83b7.png)

**Comment by gdonald** [comment]
Sorry this took so long to fix.  I didn't see the issue until today, must have missed the email.
